name: simple-ci
run-name: ${{ github.actor }} is doing GitHub Actions
on: [push]
jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python3 regexp.py
      - run: if cmp -s text.txt text_test.txt; 
          then echo "Test passed";
          else exit 1;
          fi
        shell: sh
        
  code_analise:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=andrey
            -Dsonar.projectKey=EVOLUTION666_Lab4
            -Dsonar.sources=.
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

