name: simple-ci
run-name: ${{ github.actor }} is doing GitHub Actions
on: [push]
jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python3 regexp.py
      - run: if cmp -s text.txt text_test.txt; 
          then echo "Test passed";
          else exit 1;
          fi
        shell: sh
