name: simple-ci
run-name: ${{ github.actor }} is doing GitHub Actions
on: [push]
jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip &&
          pip install -U pytest coverage
      - name: Test programm
        run: |
          coverage run -m pytest pr4_pytest.py
      - run: |
          python3 pr4.py
      - run: if cmp -s text.txt text_ep.txt; 
          then echo "Test passed";
          else exit 1;
          fi
        shell: sh
      - name: Coveral analise
        run: |
          coverage lcov
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
